# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: False
  tags: provision

  tasks:
    - name: Provision a set of instances
      ec2:
        key_name: "{{keypair}}"
        group: "{{security_group}}"
        instance_type: "{{instance_type}}"
        image: "{{ ami_id }}"
        region: "{{ec2_region}}"
        vpc_subnet_id: "{{vpc_id}}"
        assign_public_ip: true
        wait: true
        exact_count: 1
        count_tag:
           Name: Test
        instance_tags:
           Name: Test
      register: ec2

    - name: Add instance to local host group
      lineinfile: 
        dest: "./staging" 
        regexp: "{{ item.public_dns_name }}" 
        insertafter: "[launched]" 
        line: "{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: 
        host: "{{ item.public_dns_name }}"
        port: 22 
        delay: 60 
        timeout: 320 
        state: started
      with_items: ec2.instances

- hosts: launched
  name: configuration play
  user: ec2-user
  gather_facts: true

  tasks:

     - name: Check NTP service
       service: name=ntpd state=started

